server:
  port: 8080

logging:
  path: logs
  file: userManager.log
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: root

mybatis:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kang.model
  mapper-locations:
    - mapper/*
